version: '3'

networks:
  public:
    driver: bridge
    name: ImageHost

volumes:
  rabbitmq_data:
    driver: local
  db_data:
    driver: local


services:
  rabbitMQ:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmq_data:/bitnami
    ports:
      - 15672:15672 # maybe this can be deleted
      - 5672:5672
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    restart: unless-stopped
    networks:
      - public
  mySQL:
    image: mysql:8
    command: --init-file /data/application/init.sql
    container_name: likes_db
    networks:
      - public
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3306:3306

  likes:
    build: .
    container_name: likes
    networks:
      - public
    depends_on:
      - mySQL
    ports:
      - 8080:80
      - 3000:3000
    env_file: .env
    environment:
      - AMQP_URI=amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT}
      - MYSQL_URI=jdbc:mysql://likes_db:3306/${MYSQL_DATABASE}
    restart: unless-stopped